from pathlib import Path
import json,importlib.util,runpy
W=Path(__file__).resolve().parent;C=W.parents[1]
defs=[
('convlstm','ConvLSTM：卷積門控更新空間記憶','新影格和舊狀態，逐位置決定記住什麼。',[('新影格與前一步空間狀態','conv-input'),('門控保留舊值、加入新值','conv-gate'),('新狀態傳到下一時間點','conv-next')],'同一夾爪與方塊依序張開、接近、夾住。X_t及H_(t-1)以卷積產生門控，C_t=f_t⊙C_(t-1)+i_t⊙候選；H_t=o_t⊙tanh(C_t)。原論文可有peephole。給定單位置Cprev=.4,f=.5,i=.8,candidate=.5得C=.6；其餘位置另有值。不是每張影格都重新歸零；任务頭另訓練。','https://arxiv.org/abs/1506.04214'),
('videomae','VideoMAE：遮時空塊，訓練補像素','補像素訓練表示，部署另接任務頭。',[('同一格位置跨時間遮蔽','mae-tube'),('可見token編碼再解碼','mae-decode'),('只比被遮位置的像素','mae-loss')],'原版VideoMAE預訓練使用跨時間一致tube mask，通常90–95%高比例；圖中小格只示意對位，不代表實際比例。編碼器處理可見tokens，輕量解碼器加入mask tokens重建像素，以原遮蔽位置像素監督；下游動作分類使用編碼器及另外訓練任務頭，不使用預訓練解碼器。','https://arxiv.org/abs/2203.12602'),
('v-jepa','V-JEPA：預測同位置的目標特徵','目標特徵提供訓練訊號，部署另學任務。',[('可見區編碼並指定遮蔽位置','jepa-context'),('完整影片產生停止梯度目標','jepa-target'),('同遮蔽位置比較特徵差','jepa-loss')],'2024原版V-JEPA；上下文編碼器讀可見tokens，預測器加遮蔽位置資訊預測目標tokens。完整影片只進目標編碼器，目標stop-gradient，其權重由上下文EMA更新。L1比較同位置特徵。作者兩維算例預測[.2,.8]目標[.4,.7]平均絕對差.15，不是異常分數。','https://arxiv.org/html/2404.08471v1'),
('defectfill','DefectFill：學缺陷，再填指定區域','先學缺陷外觀，再核對合成位置與真實性。',[('少量缺陷與遮罩教LoRA','fill-learn'),('正常板加指定遮罩生成','fill-generate'),('遮罩內感知差異挑候選','fill-select')],'同一上方雙孔板，下方中心刮傷。少量缺陷及mask微調文字編碼器及attention LoRA；缺陷/物件/attention三損失協同。正常影像+mask進inpainting，LFS挑遮罩內相對原正常图LPIPS更大的候選（較低保真）；給定.1/.3只是示例，不等於物理真實度，仍需逐件位置及真缺陷驗證。','https://arxiv.org/html/2503.13985v1'),
('anomalydiffusion','AnomalyDiffusion：外觀與位置共同引導','逐區核對合成缺陷，不能只相信指定遮罩。',[('外觀嵌入與遮罩空間嵌入','ano-condition'),('較弱區域得到更多注意','ano-feedback'),('背景融合與圖像遮罩核對','ano-result')],'同上方双孔板，大左下/小右下兩區。學異常外觀embedding及mask編碼器，固定擴散主幹；空間及外觀條件引導。AAR用生成估計與正常圖遮罩內差找較弱區域調注意力，背景與正常圖融合。給两mask只生成一傷仍是需剔除的錯標反例，不聲稱自適應必成功。','https://arxiv.org/html/2312.05767v1'),
('tf-idg','TF-IDG：梯度引導生成，不改模型權重','更新生成中的潛變量，模型權重保持固定。',[('正常板、缺陷參考與局部遮罩','tf-input'),('特徵差的梯度引導潛變量','tf-gradient'),('補弱區並保持背景紋理','tf-result')],'同中部兩孔板，下方兩刮傷區。TF-IDG固定預訓練權重；生成局部特徵與參考對齊，梯度對latent求得並進入採樣更新，不是optimizer更新模型權重。自適應遮罩補弱區，AdaIN及背景融合保持紋理；跨材質參考仍可能錯。官方cldm/ddim_hacked.py autograd.grad(loss,latent)可核對；圖中z→z_next只示意引導不是完整採樣公式。','https://github.com/rubymiaomiao/TF-IDG ; https://raw.githubusercontent.com/rubymiaomiao/TF-IDG/main/cldm/ddim_hacked.py'),
('controlnet','ControlNet：控制殘差接入去噪主幹','條件控制布局，細節仍要回原條件核對。',[('雙孔輪廓形成控制條件','control-input'),('可訓練分支經零初始化連接','control-inject'),('多步條件去噪再比輪廓','control-result')],'同上方雙孔矩形板，輪廓圖含外框/兩孔，文字指定銀色金屬。預訓練主幹固定，可訓練編碼副本接條件，zero convolution初始化0以殘差連接主幹；訓練後連接通常不為0。每步讀時間/噪聲latent與條件；不把輪廓輸出當缺陷熱點。','https://arxiv.org/abs/2302.05543'),
('inpainting','Inpainting：指定內區，保留外部上下文','編修影像可以補平，實物狀態並未改變。',[('原圖與可編修遮罩分開保存','paint-input'),('遮罩內去噪、外部提供上下文','paint-process'),('檢查接縫與遮罩外變動','paint-check')],'同上方雙孔板，下方污點為可編修區。以擴散修補為例，原圖與二值mask定義位置；mask 1為修改的本圖約定，API可能相反。生成內區與外部上下文融合，不保證所有pipeline遮罩外逐像素不變；比較原圖與編修版並另存。真孔被影像填平不代表實體補材。','https://arxiv.org/abs/2201.09865'),
('diffusion-restoration','擴散復原：估計後，套回觀測條件','退化後相符是必要核對，不能證明細節唯一。',[('同板退化觀測與退化算子','restore-observe'),('先驗與觀測共同約束候選','restore-candidate'),('候選再退化，回比原觀測','restore-check')],'同中部雙孔板。以線性退化y=Ax+n為例，預訓練擴散先驗與已知觀測/退化條件形成候選；不同方法條件接法不同，不概括為單一演算法。作者兩像素平均算子：[0,100]及[40,60]都得50，證明非唯一；不把某次採樣當真值。','https://arxiv.org/abs/2201.11793'),
('deblur','Deblur：模糊邊緣反推清晰候選','清晰候選仍要用獨立觀測檢查假邊。',[('移動曝光使邊緣展寬','blur-forward'),('由觀測估計清晰邊緣','blur-inverse'),('回看振鈴及獨立清晰影像','blur-check')],'同金屬板直邊橫切，真邊階躍與曝光平均展寬。傳統反卷積/學習式復原均輸出估計，圖示非某一特定模型架構；空間變化運動模糊不能用單一核概括。回套退化及獨立短曝光影像檢查重影/振鈴。不用可能缺字的近似符號，直接寫約等於。','https://arxiv.org/abs/1612.02177'),
('super-resolution','超解析：由低採樣估計高解析候選','更多輸出像素，不等於更多相機觀測。',[('同一矩形雙孔板的粗採樣','sr-low'),('插值與學習估計各自放大','sr-estimate'),('縮回低解析核對一致性','sr-check')],'維持大左孔/小右孔矩形板，固定左孔邊q。低解析格可經插值或學習先驗變高解析；輸出細節是估計。給定局部兩子像素[20,80]與[40,60]平均同50，只說明非唯一，不聲稱這兩例直接對應有缺口/無缺口。指定主反例也改矩形同板同q。','https://arxiv.org/abs/2104.07636')]
def brief(r):
 return '# '+r['title']+'\n- lesson objective: '+r['takeaway']+'\n- page type: '+r['kind']+'\n- primary reading path: '+' → '.join([p['title'] for p in r['panels']]+[r['takeaway']])+'\n- named guide-conformant reference page: `teaching-images/vision-ai-model-selection/course-delivery/section-pages/01-geometry-alignment-measurement/images/final/GEO-02-common-contract_v01.png`\n- pale-yellow takeaway: '+r['takeaway']+' #FFF4CC\n- major visual nodes:\n'+'\n'.join(f"  {i+1}. {p['title']}" for i,p in enumerate(r['panels']))+'\n'+r['detail']+'\n來源：'+r['source']+'\n模式：新SVG→PNG作者機制示意，非本輪模型推論。11課原首讀桌機與V-JEPA/SR手機已實看；夾爪方塊、各課矩形板孔位/缺陷位置保持原身份。\n權威：CLAUDE.md、IMAGE_STYLE_GUIDE.md、TEACHING_REVIEW_LOG.md、TEACHING_SCORING_RUBRIC.md、TEACHING_WEBPAGE_GUIDE.md。\nPNG review pending；page review pending；user approval pending。\n'
if __name__=='__main__':
 spec=importlib.util.spec_from_file_location('v',C/'tools/validate_teaching_preflight.py');v=importlib.util.module_from_spec(spec);spec.loader.exec_module(v)
 rows=json.loads((W/'engineering-plan.json').read_text(encoding='utf-8'));out=[]
 for o,title,take,panels,detail,source in defs:
  id=o+'-engineering-2';assert not any(r['id']==id for r in rows)
  r=dict(id=id,owner=o,index=2,version='r01',kind='C',title=title,takeaway=take,mobile_height=2304,panels=[dict(title=a,graphic='b7-'+b) for a,b in panels],detail=detail,source=source,terms=['示意數值：作者給定局部算例，非模型實測或建議參數。','同位置：比較保持相同影像座標與時間身份，不能任意換工件。']);rows.append(r);p=W/(id+'-r01.md');p.write_text(brief(r),encoding='utf-8');out.append(v.validate(p))
 (W/'engineering-plan.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf-8');(W/'batch7-prototype-preflight-validation.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
 (W/'checkpoint-note.md').write_text('### WI-033 第七批11課機制preflight\n\n第六批來源/docs建置成功1370資產，32狀態與8回歸正在跑；頁內實看未完，完成仍33/52。第七批11課原主圖已實看、原論文/官方TF-IDG梯度程式核對；11機制preflight通過，即將建立SVG並渲染22PNG，尚未審/整合。SR反例需同矩形板，V-JEPA頁內圖說間距待驗；33擴展故事未做。全部52課持續，使用者核准pending。\n',encoding='utf-8');runpy.run_path(str(W/'append-checkpoint.py'))
