from pathlib import Path
import json,runpy,importlib.util
W=Path(__file__).resolve().parent;C=W.parents[1];p=W/'engineering-plan.json';rows=json.loads(p.read_text(encoding='utf-8'));m=runpy.run_path(str(W/'plan-batch7-prototypes.py'));owners=[d[0] for d in m['defs']];proto={r['owner']:r for r in rows if r['owner'] in owners and r['index']==2}
def add(o,n,title,take,panels,detail,kind='C'):
 rid=o+'-engineering-'+str(n);assert not any(r['id']==rid for r in rows)
 rows.append(dict(id=rid,owner=o,index=n,version='r01',kind=kind,mobile_height=2304,title=title,takeaway=take,panels=[dict(title=a,graphic='b7-'+b) for a,b in panels],detail=detail,source=proto[o]['source'],terms=proto[o]['terms'],review='pending'))
add('convlstm',1,'ConvLSTM：影片狀態接上明確任務','時序表示要接任務頭，才有可驗的輸出。',[('連續夾取影片與任務標註','video-labels'),('卷積記憶接任務頭','conv-head'),('完整影片驗失敗與延遲','video-validation')],'同夾爪方塊，夾取成功/失敗是另定義標籤；ConvLSTM產生H/C，分類頭需有監督。以整段影片或實體工件切分，不讓相鄰幀跨訓練驗證。')
add('convlstm',3,'ConvLSTM：狀態生命週期要明定','換影片或相機時，依任務重設記憶。',[('順序、幀距與縮放固定','video-timing'),('同片續接，換片重設','conv-reset'),('保存狀態與任務頭版本','conv-contract')],'推論狀態初始化/持續/重設需符合訓練方式；不能讓相機A記憶污染B。保存幀距、解析度、網路及任務頭版本，量完整預處理/狀態更新/任務輸出延遲。')
add('convlstm',4,'ConvLSTM：有記憶也可能忘記關鍵','記憶是一種可學狀態，不是完整影格存檔。',[('短暫失敗發生在中間影格','video-missed'),('忘記門連乘使舊訊號衰減','conv-decay'),('不同片長與幀距各自驗','video-validation')],'作者單格例：後續不加入新候選，C初值1、每步f=.5，經三步變.125；不代表真模型門固定。關鍵事件若未取到/遭遺忘仍可能漏檢。','D')
add('videomae',1,'VideoMAE：預訓練與分類分工','預訓練學表示，標註任務教答案。',[('未標註影片遮蔽重建','mae-pretrain'),('標註影片訓練分類頭','video-head'),('新影片輸出任務類別','video-delivery')],'重建預訓練不直接定義夾取失敗；下游以標註片段微調或固定編碼器學頭，必須明列模式。部署用新影片與分類路徑。')
add('videomae',3,'VideoMAE：token與取樣決定成本','減少取樣可省成本，也可能漏掉短事件。',[('固定片長、幀距與裁切','video-timing'),('時空token數影響注意力','video-token-cost'),('同硬體驗事件召回與延遲','video-validation')],'全注意力成對數約隨N平方；給定100與200 tokens，其N平方1萬/4萬只是計算量尺度示例，不是實測毫秒。取樣跨距大可能漏短失敗。')
add('videomae',4,'VideoMAE：補得像，不保證分類對','像素重建與任務判斷必須分開驗。',[('背景很像，夾取卻失敗','video-failure'),('平均像素差可能掩小事件','mae-error-average'),('依事件留出驗任務頭','video-validation')],'作者例：100格中99格平方差0、關鍵格100，平均1；平均重建差不能直接當事件成功率。少數關鍵動作需標註與下游驗證。','D')
add('v-jepa',1,'V-JEPA：特徵預測之後再學任務','自監督訊號不會自動變成事件標籤。',[('未標註影片學特徵預測','jepa-pretrain'),('標註夾取影片教任務頭','video-head'),('新片特徵交任務判斷','video-delivery')],'原版2024 V-JEPA預測表徵而非像素；下游可固定骨幹學注意力探針，或另選微調策略須記清。目標編碼器和預測器不是部署任務頭。')
add('v-jepa',3,'V-JEPA：保存取樣與下游模式','骨幹、讀出頭與取樣設定是一組。',[('固定時空取樣','video-timing'),('固定骨幹或微調需寫明','jepa-contract'),('片長、事件和延遲一起驗','video-validation')],'保存2024骨幹checkpoint、影格取樣、裁切與下游讀出頭。EMA是預訓練目標權重更新，不是現場每片自動更新模型；原版不宣稱未來影像生成。')
add('v-jepa',4,'V-JEPA與VideoMAE：監督目標不同','同影片比較任務成果，不能比兩種損失值。',[('同一夾取影片與同一標籤','video-labels'),('VideoMAE對像素平方差','compare-pixel'),('V-JEPA對目標特徵L1差','compare-feature')],'兩者預訓練目標及尺度不同，L1=.15不能對MSE=1排名。固定資料、讀出方式、硬體與事件指標比較；沒有本輪共同實測。','D')
add('defectfill',1,'DefectFill：合成資料先核對再加入','合成圖供訓練增補，真實留出集負責驗收。',[('少量真缺陷及人工遮罩','fill-dataset'),('同板指定位置產生刮傷','fill-generate'),('檢查後納入訓練資料','fill-handoff')],'正常底圖、參考缺陷、遮罩與來源保留；合成圖及mask一致才進訓練。真實缺陷留出不得被參考/候選挑選用過。')
add('defectfill',3,'DefectFill：適配與挑選成本分開算','候選越多，生成與挑選的成本都會累積。',[('保存LoRA與遮罩版本','fill-contract'),('多候選乘上多步採樣','generation-cost'),('挑選仍需真缺陷驗證','fill-validation')],'保存基模/LoRA、文字、mask、種子、採樣與LFS設定。作者例4候選×20步=80去噪呼叫，未含LPIPS與預處理；增加候選不保證增加資料效益。')
add('defectfill',4,'DefectFill：局部差大，也可能是假傷','LFS挑局部差異，物理合理性仍需另驗。',[('同板同位置的刮傷候選','fill-select'),('異常大黑塊也可能差很大','fill-artifact'),('用真實缺陷留出驗效益','fill-validation')],'感知距離較大也可能來自不合理塗塊，不等於真刮傷。以mask覆蓋、材質及真缺陷檢測效益核對。','D')
add('anomalydiffusion',1,'AnomalyDiffusion：兩區各有資料責任','圖與遮罩要逐區一致，才可當訓練樣本。',[('真缺陷教外觀與位置','ano-dataset'),('同板雙區條件生成','ano-condition'),('逐區驗證圖與標註','ano-pair-check')],'保持原上方雙孔板及大左下小右下兩傷。合成mask是生成條件，不自動成為真值；空mask區或越界都要剔除或修標。')
add('anomalydiffusion',3,'AnomalyDiffusion：外觀與位置都要版本','保存嵌入、遮罩編碼與採樣設定。',[('外觀與遮罩編碼配套保存','ano-contract'),('逐區看生成變化強弱','ano-feedback'),('兩個區域分開量覆蓋','ano-pair-check')],'保存基模、外觀embedding、mask編碼、AAR/背景融合與採樣設定。不同大小缺陷不能只看整圖平均；位置覆蓋與背景孔位分開驗。')
add('anomalydiffusion',4,'AnomalyDiffusion：兩個遮罩只長一傷','未生成的區域，不能沿用缺陷標籤。',[('條件指定左大右小兩區','ano-two-masks'),('反例只生成左側刮傷','ano-one-defect'),('剔除或修標，再驗訓練效益','ano-reject')],'同板同mask，一傷對兩標籤是錯標反例；AAR可能改善但不保證避免。不得用合成量取代真實留出集。','D')
add('tf-idg',1,'TF-IDG：參考外觀引導局部合成','不微調權重，仍需要參考、遮罩與驗證。',[('正常板、參考傷、局部遮罩','tf-input'),('固定權重下引導latent','tf-gradient'),('同板兩區逐一核對','tf-delivery')],'免微調不是零資料。正常底圖與外觀參考及mask是每次生成條件；同中部雙孔板下方兩區，保存合成來源。')
add('tf-idg',3,'TF-IDG：免訓練仍有反向計算','每步特徵梯度也要算進延遲與記憶體。',[('模型權重固定且不更新','tf-fixed'),('latent求導需中間激活','tf-autograd-cost'),('保存參考與引導設定','tf-contract')],'官方autograd.grad(loss,latent)是採樣引導；不要把免微調等同只有一次前向。計入特徵、梯度、採樣與背景融合時間；未實測不給速度排名。')
add('tf-idg',4,'TF-IDG：参考換材質，可能帶錯紋理','梯度對齊外觀，不保證符合目標材質。',[('金屬板與木紋缺陷參考','tf-material'),('生成區帶入木紋反例','tf-contamination'),('同材質真例檢查孔位與紋理','tf-delivery')],'作者失敗示意：木紋參考可能使金屬局部出現木質纹理；背景保持不能保證mask內物理正確。','D')
add('controlnet',1,'ControlNet：條件圖與文字共同交付','先定義控制什麼，再檢查生成是否遵守。',[('保存雙孔輪廓與文字','control-input'),('條件版本接匹配模型','control-contract'),('生成板回比孔位與外框','control-overlay')],'輪廓抽取版本、解析度與對應ControlNet checkpoint需匹配。輸出是合成板，不是實拍檢測或尺寸量測。')
add('controlnet',3,'ControlNet：控制強度要配採樣驗證','強度只是設定，遵守條件與品質要同時看。',[('保存控制模型與前處理','control-contract'),('控制強弱改變殘差注入','control-strength'),('同條件比較位置偏差','control-overlay')],'保存前處理器、控制強度/起止步、基模、文字與採樣。強度增大不保證所有細節更真；用同輪廓檢孔位/外框及材質。')
add('controlnet',4,'ControlNet：相同輪廓，不限定有無刮傷','條件未描述的細節，不能當成觀測證據。',[('同一張雙孔輪廓條件','control-input'),('無傷與有傷都可符輪廓','control-two-surfaces'),('若要真缺陷，回實拍核對','control-real-check')],'同上方兩孔，外框與孔位不變，表面刮傷可不同；輪廓相符不能證明生成裂紋真實存在。','D')
add('inpainting',1,'Inpainting：原圖、遮罩、候選三者留存','編修輸出另存，保留原觀測供追查。',[('原污點影像與修改範圍','paint-input'),('遮罩與模型約定核對','paint-contract'),('候選與原圖並列驗接縫','paint-check')],'同上方雙孔板下方黑污點，明列mask 1修改約定及預處理縮放，保存原圖與生成版本。')
add('inpainting',3,'Inpainting：遮罩太緊或太大各有代價','按原位置驗接縫、孔位與遮罩外變化。',[('緊遮罩保留邊缘污點','paint-tight'),('大遮罩可能波及鄰近結構','paint-wide'),('保留原圖與mask縮放記錄','paint-contract')],'遮罩需包含預期修改區；羽化/膨脹可能改善接縫也擴大修改範圍，實作各異。不能推薦固定像素寬度。')
add('inpainting',4,'Inpainting：照片填孔，實體仍有孔','影像編修只改像素，不能當實物修復。',[('原板左上孔指定可編修','paint-real-hole'),('生成版孔被紋理填平','paint-filled-hole'),('重新拍攝仍看見真孔','paint-recapture')],'同上方兩孔板，仅改左孔影像。原檢測與實物量測不能拿編修版本作真值。','D')
add('diffusion-restoration',1,'擴散復原：先說清楚觀測退化','復原候選與原始觀測需一起交付。',[('保存原板影像與退化條件','restore-observe'),('觀測條件約束先驗候選','restore-candidate'),('回套退化並另作外部驗證','restore-delivery')],'線性逆問題示意，保存A/噪聲假設與原觀測；候選再退化對回y並檢未觀測細節，不把低殘差當真值。')
add('diffusion-restoration',3,'擴散復原：退化假設與採樣要配套','不同退化條件，不能只換同一張結果圖。',[('退化算子與噪聲設定版本','restore-contract'),('同觀測保留多個候選','restore-multiple'),('比較資料一致性與外部證據','restore-delivery')],'保存模型、退化算子、噪聲與步數種子；不同候選一致不保證唯一真實。時間要含每步去噪及資料一致性。')
add('diffusion-restoration',4,'擴散復原：錯退化也會給漂亮結果','先驗看起來合理，仍可能不符合取像原因。',[('原板實際受雜訊污染','restore-observe'),('錯把觀測當移動模糊','restore-wrong-a'),('回原觀測和取像設定核對','restore-delivery')],'作者反例把加性雜訊當卷積模糊，假設錯誤可引入不必要輪廓。需檢退化與獨立成像，不以漂亮結果證明模型合適。','D')
add('deblur',1,'Deblur：模糊觀測與清晰參考分开','去模糊是估計，量測需驗邊緣偏差。',[('保存模糊直邊與曝光設定','blur-source'),('以復原模型估計清晰候選','blur-inverse'),('同位置與清晰取像比對','blur-check')],'同板直邊，不只比較視覺清晰度；以同位置獨立短曝光/清晰圖驗邊緣偏移、假邊與下游量測。')
add('deblur',3,'Deblur：速度、細節和假邊一起驗','按實際曝光與運動條件驗完整流程。',[('保存解析度、曝光與模型','blur-contract'),('逐位置比較邊緣偏移','blur-position'),('端到端延遲與錯誤一起看','blur-validation')],'物理移動/失焦與空間變化不同，模型訓練退化需對應。作者像素邊界100/102差2只示例，不是毫米或模型實測。')
add('deblur',4,'Deblur：銳利的多重邊可能是振鈴','銳利度增加，不能取代真邊位置證據。',[('原觀測只有一條模糊邊','blur-source'),('候選多重邊造成錯定位','blur-ringing'),('独立清晰取像驗單一真邊','blur-check')],'同邊橫切振鈴比原平滑觀測更銳利但有額外輪廓，量測若選錯峰會偏移。獨立成像驗證。','D')
add('super-resolution',1,'超解析：輸入採樣與輸出像素分清','輸出更密，仍要保留原始低解析影像。',[('矩形板左孔q的粗採樣','sr-low'),('插值或學習先驗放大','sr-estimate'),('另存候選與原採樣條件','sr-contract')],'同矩形板大左小右孔，固定q；保存原解析度、縮放倍率、退化假設與模型版本，輸出不是新增相機資料。')
add('super-resolution',3,'超解析：倍率改變像素量與成本','放大倍率和真實細節改善要分開驗。',[('寬高各兩倍，像素變四倍','sr-pixel-cost'),('保存模型與低解析來源','sr-contract'),('真實高解析取像驗q細節','sr-real-check')],'作者100×100到200×200由1萬到4萬像素，只是存儲/輸出量，不保證速度固定四倍。需實测延遲與細節保真，沒有本輪實測。')
add('super-resolution',4,'超解析：插值與生成如何取捨','同原圖比較細節保真與成本，不只看銳利。',[('同一左孔q與低解析觀測','sr-low'),('插值不學先驗，模型估細節','sr-estimate'),('用真實高解析留出驗證','sr-real-check')],'插值成本通常較簡但不能恢復缺失細節；學習式使用先驗且可能幻覺。固定真實取像、退化、硬體與下游任務比較，不用跨論文排名。','D')
sp=importlib.util.spec_from_file_location('v',C/'tools/validate_teaching_preflight.py');v=importlib.util.module_from_spec(sp);sp.loader.exec_module(v);out=[]
for r in rows:
 if r['owner'] in owners and r['index']!=2:
  f=W/(r['id']+'-r01.md');f.write_text(m['brief'](r),encoding='utf-8');out.append(v.validate(f))
assert len(out)==33;p.write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf-8');(W/'batch7-expanded-preflight-validation.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
(W/'checkpoint-note.md').write_text('### WI-033 第七批33擴展故事preflight\n\n22機制原型原生審查已通過。33擴展preflight完成，保持各課原工件/影片身份，數值為作者算例；即將實作SVG並渲染66PNG，尚未生成或審查。SR同件主反例另待做，整合與頁面驗證未跑。完成41/52，使用者核准pending；全部52課持續。\n',encoding='utf-8');runpy.run_path(str(W/'append-checkpoint.py'))
