from pathlib import Path
import json,importlib.util,runpy
W=Path(__file__).resolve().parent;C=W.parents[1]
defs=[
('ad-dinomaly','Dinomaly：限制照抄，再分組比較','訓練擾動與分組對照，要和推論設定分開。',[('正常特徵，訓練才Dropout','dino-drop'),('線性注意力分散聚合','dino-linear'),('多層分組後比較差異','dino-groups')],'固定DINOv2，用正常特徵訓練瓶頸及解碼器；訓練MLP Dropout阻止直接照抄，eval關閉。線性注意力降低聚焦相同位置的捷徑；多層按組相加後比較，放寬逐層對應。訓練另降低已重建良好位置的梯度影響。圖中兩組/小格為機制示意，不是固定層號或維度。','https://arxiv.org/html/2405.14325v5'),
('ad-invad','InvAD：空間條件，逐位置調制','同一輸入形成空間條件，控制特徵重建。',[('輸入特徵轉成空間條件','inv-condition'),('同一標準化值，不同調制','inv-modulate'),('重建特徵回比原表示','inv-compare')],'本課為2024 Feature Inversion的InvAD。固定影像編碼器抽特徵，融合/重縮放/風格轉換產生空間條件；由常數特徵起步，SSM以每位置縮放和偏移調制標準化特徵。给定z=3，p縮放2偏移1得7，q縮放0.5偏移0得1.5；這只是SSM局部算例。正常訓練MSE重建，推論餘弦差。SSM是Spatial Style Modulation，不是狀態空間模型。','https://arxiv.org/html/2404.10760v1'),
('ad-ddad','DDAD：原圖引導，每步逐漸去噪','恢復估計與原圖的兩種差異，共同提供線索。',[('待測原圖持續提供條件','dd-guide'),('多步去噪形成恢復估計','dd-steps'),('像素與適配特徵各自比較','dd-compare')],'正常影像訓練去噪及適配特徵比較；測試以待測原圖引導每步去噪，得到恢復估計R。原A與R同位置的像素差和適配特徵差加權形成位置線索；恢復不是正常真值，圖中三狀態不是固定採樣步數，也不是本輪模型結果。','https://arxiv.org/abs/2305.15956'),
('ad-winclip','WinCLIP：視窗分數，依覆蓋位置聚合','文字定狀態，視窗分數依覆蓋回到位置。',[('人工狀態詞與句型組合','win-prompts'),('同圖的重疊視窗讀局部','win-windows'),('同位置視窗分數調和平均','win-harmonic')],'固定CLIP，人工正常/異常狀態詞與句型組合產生文字表示；每視窗整體表示與文字比相似。分數分給視窗所覆蓋位置，同位置重疊視窗使用調和平均，再融合多尺度。給定同尺度兩窗0.2/0.8，在共同覆蓋p的平均為2/(1/0.2+1/0.8)=0.32，不是算術平均0.5，也不是缺陷機率。','https://arxiv.org/html/2303.14814v1'),
('ad-anomalyclip','AnomalyCLIP：先學提示，再定位新件','目標零樣本，仍有輔助資料學習的提示。',[('輔助產品教正常與異常提示','ac-train'),('同件特徵比學到的兩狀態','ac-match'),('局部定位與整圖分數分工','ac-local')],'輔助資料的正常/異常及局部標註學物件無關提示；CLIP骨幹權重固定。目標影像使用已學提示，DPAM調整注意力以保留局部語意；整圖與局部監督互補。目標零樣本指目標資料未參與提示訓練，不等於整套未訓練，也不等於不用獨立驗證。','https://arxiv.org/html/2310.18961v3'),
('frame-difference','Frame Difference：同座標相減，留下雙帶','雙帶來自同物件前後位置，不能當兩個物件。',[('同一方件，前後移動一格','fd-frames'),('固定座標，逐格取絕對差','fd-values'),('只有離開與進入兩帶亮','fd-bands')],'給定一維橫切灰階：前幀[20,100,100,100,20]，後幀[20,20,100,100,100]，差[0,80,0,0,80]。方件向右移一格，中間重疊不變；兩條亮帶是同一物件的離開與進入，不是兩物件或完整輪廓。教學算例未跑影像演算法。','https://docs.opencv.org/4.x/d2/de8/group__core__array.html'),
('background-subtraction','背景相減：累積常態，再比較現在','前景依賴背景歷史，停留物件也可能被吸收。',[('不同時間累積背景常態','bg-history'),('目前影格比較同位置背景','bg-compare'),('持續更新可能吸收停留物件','bg-update')],'以MOG2為例，同位置累積常見外觀的混合高斯模型，當前影像相對背景分類前景。方件長期停留時可能成為背景，前景遮罩下降；不是只和上一幀相減。更新速率/歷史/陰影處理影響結果，圖中示意不是固定吸收時間。','https://docs.opencv.org/4.x/d1/dc5/tutorial_background_subtraction.html'),
('bytetrack','ByteTrack：先高分，再接剩餘低分','低分框要有軌跡依據，才可能接回原ID。',[('每幀框分高分與低分','byte-detections'),('先高分，再補未配對軌跡','byte-match'),('接回ID或標成暫時丟失','byte-life')],'偵測框分高/低分，先以高分框匹配預測軌跡，再用低分框匹配剩餘未配對的活動軌跡。給定ID7短暫遮擋造成0.3低分但位置接近，可第二輪續接；孤立低分不直接建新ID。未接回則丟失，超過保留期移除；計數線與事件由下游另訂。分數只是算例，非建議門檻。','https://github.com/FoundationVision/ByteTrack')]
def brief(r):
 return '# '+r['title']+'\n- lesson objective: '+r['takeaway']+'\n- page type: '+r['kind']+'\n- primary reading path: '+' → '.join([p['title'] for p in r['panels']]+[r['takeaway']])+'\n- named guide-conformant reference page: `teaching-images/vision-ai-model-selection/course-delivery/section-pages/01-geometry-alignment-measurement/images/final/GEO-02-common-contract_v01.png`\n- pale-yellow takeaway: '+r['takeaway']+' #FFF4CC\n- major visual nodes:\n'+'\n'.join(f"  {i+1}. {p['title']}" for i,p in enumerate(r['panels']))+'\n'+r['detail']+'\n來源：'+r['source']+'\n模式：新SVG→PNG；八課原首讀桌機已逐張實看，異常金屬板維持大小孔及右側刮傷，影片維持方件/ID7的L標記。先機制原型再擴展。\n權威：CLAUDE.md、IMAGE_STYLE_GUIDE.md、TEACHING_REVIEW_LOG.md、TEACHING_SCORING_RUBRIC.md、TEACHING_WEBPAGE_GUIDE.md。\nPNG review pending；page review pending；user approval pending。\n'
spec=importlib.util.spec_from_file_location('v',C/'tools/validate_teaching_preflight.py');v=importlib.util.module_from_spec(spec);spec.loader.exec_module(v)
if __name__=='__main__':
 rows=json.loads((W/'engineering-plan.json').read_text(encoding='utf-8'));out=[]
 for o,title,take,panels,detail,source in defs:
  id=o+'-engineering-2';assert not any(r['id']==id for r in rows)
  r=dict(id=id,owner=o,index=2,version='r01',kind='C',title=title,takeaway=take,panels=[dict(title=a,graphic='b6-'+b) for a,b in panels],detail=detail,source=source,terms=['位置：對回同一輸入座標，不能任意混層或混影格。','圖中數值：作者給定機制算例，非模型實測或建議門檻。']);rows.append(r);p=W/(id+'-r01.md');p.write_text(brief(r),encoding='utf-8');out.append(v.validate(p))
 (W/'engineering-plan.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf-8');(W/'batch6-prototype-preflight-validation.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
 (W/'checkpoint-note.md').write_text('### WI-033 第六批八機制preflight完成\n\n第五批已建置1370資產958.7MB，32主頁/回歸執行中，深讀與頁內審尚未完成。第六批原主圖8張與CLIP共用手機2張已實看，原論文核對；八機制preflight通過。即將生成16PNG，尚未審或整合；24擴展與2共用手機待做。完成25/52，全部52課持續，使用者核准pending。產物workitems/wi-033。\n',encoding='utf-8');runpy.run_path(str(W/'append-checkpoint.py'))
