from pathlib import Path
import json,sys
W=Path(__file__).resolve().parent; C=W.parents[1]
REF='teaching-images/vision-ai-model-selection/course-delivery/section-pages/01-geometry-alignment-measurement/images/final/GEO-02-common-contract_v01.png'
rows=[]
def add(id,owner,title,kind,nodes,takeaway,scene,source):
 rows.append(dict(id=id,owner=owner,title=title,kind=kind,nodes=nodes,takeaway=takeaway,scene=scene,source=source))
add('charuco-core','charuco','ChArUco：用已知角點，建立相機幾何','C',['已知標靶','跨視角對應','估參數與驗證'],
 '先用多視角建立內參；已知內參後才另外求姿態。',
 'Three stages. Left: plausible camera lens and one printed ChArUco board, checkerboard with square fiducials inside white squares, no meaningless PCB. Enlarge ONE chessboard intersection, NOT marker center, with label「角點A」 and known board coordinates「板上位置已知」. Mid: same board photographed at 3 different tilts/positions inside same camera image boundary; same A corner marked. Connect board corner identity to image A identity using dotted correspondence lines, not temporal arrows. Label「多視角角點對應」. Right: clearly separated vertical substeps: calibration gives「相機內參＋畸變」beside a camera and distorted grid becoming rectified grid; then a SEPARATE arrow labeled「內參固定後」into pose estimation using one observed board and known board points, outputs board axes labeled「姿態R/t」. A small same-corner observed dot vs projected hollow dot pair labeled「重投影核對」joins validation, no invented precision. Calibration is not registration of daily product images. Board illustrations are conceptual, not printable calibration targets. Concrete board and visible corner identities occupy most area.',
 'https://docs.opencv.org/4.13.0/da/d13/tutorial_aruco_calibration.html')
add('charuco-failure','charuco','只拍中心，邊角誤差可能沒有被看見','D',['同一相機與標靶','中心集中與廣泛覆蓋','用未參與校正的視角核對'],
 '校正要涵蓋位置與傾角；再用獨立視角查邊角誤差。',
 'Same ChArUco board same camera lens. Three conceptual regions: common camera/board input, large paired image-coordinate maps, independent check. In paired maps identical rectangular field-of-view: LEFT all small board corner observations clustered near center; RIGHT corner observations cover center and four outer regions with several tilts. Draw clearly different coverage, not different color of same dots. Label「只拍中心」「位置＋傾角都涵蓋」. Same unseen tilted board at field edge in final region with enlarged corner observed dot vs projected ring separated, label「邊角獨立核對」and action「不足就補拍」. Do NOT promise widespread coverage always passes; all results are conceptual. No exact score or invented statistics, no guarantee of metric measurement.',
 'https://docs.opencv.org/4.13.0/da/d13/tutorial_aruco_calibration.html')
add('ecc-failure','ecc','起點太遠，ECC可能對錯位置','D',['同一模板與待對圖','近起點與遠起點','核對整件及殘差'],
 'ECC需要合理起點；對不上就先找粗定位。',
 'Use SAME two-hole L metal bracket and same images in both alternatives. Blue solid is template outline; orange dashed is current resampled moving outline. Common input shown once at top left, identical bracket and two holes. Two large parallel comparison regions:「合理起點」has near overlap then aligned hole pair;「起點太遠」has initial shifted bracket with only partial overlap then mismatched one hole-to-other-hole alignment. The bracket itself must not vanish or lose a hole. Show entire bracket outlines and a same-location inset to reveal wrong hole correspondence. Orange warning in wrong alignment「局部像，不代表整件對」. Final small action area shows feature point correspondences to coarse alignment then fine refinement, label「先粗定位，再微調」. No performance numbers. Do not show arbitrary failures as actual experiment. Emphasize different initialization, same source images.',
 'https://docs.opencv.org/4.13.0/dc/d6b/group__video__track.html')
add('sift-core','sift','SIFT：用局部方向線索，找兩張圖的對應','C',['找穩定局部','方向描述與比對','交出匹配點'],
 'SIFT找的是對應點；幾何變換還要另行估計與驗證。',
 'Same asymmetric two-hole metal bracket with an upper-right notch, two views one rotated about 20 degrees and slightly rescaled. Left paired grayscale views with 3 sparse corresponding named local corners A B C, keypoint circles denote local scale. Center enlarge SAME distinctive upper-right notch patch in both views: small gradient arrows reflect edge normals; rotate local reference frame to dominant direction, then two compact multi-bin orientation histogram strips have matching shape. Label「先對齊局部方向」「整理梯度分布」and tiny「描述子示意」. Avoid whole-image rotation claimed as actual SIFT output. RIGHT two image strips with corresponding A-A B-B C-C lines; include one ambiguous repeated-hole match as dashed orange crossed-out line labeled「含糊配對先剔除」. Output label「匹配點」then clearly separate small arrow to「幾何估計另做」. No network weights or training, subtitle「演算法｜不需訓練權重｜教學示意」. Enough feature evidence to see description not just feature dots.',
 'https://docs.opencv.org/4.13.0/da/df5/tutorial_py_sift_intro.html')
add('sift-failure','sift','模糊會抹掉SIFT需要的局部線索','D',['同一工件兩視圖','清楚與模糊局部','重新取像或改定位線索'],
 '局部線索消失時，先改善影像，再談匹配數量。',
 'Same two-hole asymmetric bracket, same camera viewpoints, compare clear vs only moving image blurred. Show two large equal-scale notch patch comparisons. Clear patch retains sharp notch and directional gradient arrows with distinctive histogram peaks. Blurred patch genuinely loses notch detail, flatter weaker gradient evidence, candidate correspondence to multiple similar edge patches shown dashed orange. Label「清楚：局部可區分」「模糊：候選變含糊」. Keep bracket geometry in raw image same, blur is the only changed condition; no missing metal. End with focus/exposure setting and a sharp recaptured notch, labeled「先重拍／調整光學」, or if texture absent use known target. No invented counts, no statement four matches inherently insufficient. The matching task and subsequent geometry verification separate.',
 'https://docs.opencv.org/4.13.0/da/df5/tutorial_py_sift_intro.html')
add('lightglue-core','lightglue','LightGlue：借周圍關係，把含糊配對分清','C',['上游提供點與描述','互看上下文並修剪','匹配交給幾何估計'],
 'LightGlue學的是配對；找點與求變換仍各有負責者。',
 'Same asymmetric two-hole bracket in two views, point identities A at unique notch, B/C at two similar holes. First region show extractor detecting A B C on both images and descriptor strips, label「上游extractor」. Center dominant wide evidence: query B in left view initially connects with equally thin orange dashed links to two right hole candidates B and C. Unique notch A-A is solid blue contextual anchor. After attention refinement, B-B thick blue, wrong B-C fades gray and terminates with cross at its target; A-A maintained. SAME coordinates and holes remain before/after. Label「圖內關係＋跨圖訊息」「含糊候選 → 更新配對」; small faint difficult point removed and labeled「低可匹配點修剪」, not all unmatched points deleted from source photo. Last output two image strips with stable match lines; separate arrow to a simple geometric projected quadrilateral labeled「RANSAC／幾何估計另做」. Training weights acknowledged subtitle「學習式配對器｜教學示意」. Do not depict LightGlue finding keypoints or directly warping images. No fake numeric confidences.',
 'https://github.com/cvg/LightGlue')
add('lightglue-failure','lightglue','沒有可區分線索，學習配對也會含糊','D',['同一金屬件與兩個孔','保留定位缺口與遮住缺口','保留不確定再補證據'],
 '學習配對不能憑空補線索；含糊時要補視角或定位特徵。',
 'Same bracket with two similar holes and unique upper-right notch, two camera views. Compare EXACT same input viewpoints except a matte opaque occluder hides unique notch only in moving view on right condition. LEFT clear notch has A-A unique match supporting correct B-B hole match. RIGHT masked notch cannot be observed, two hole candidates remain same-looking and equally plausible; show two orange dashed alternatives and question mark only at correspondence, not arbitrary high confidence score. Label「缺口可見」「缺口被遮住」. The occluder must really hide notch, never transparent grid. Last region removing occlusion / another view restores unique landmark, label「補視角或已知定位點」. Keep all unoccluded holes identical positions and avoid claim LightGlue always fails or always recovers. No real output claim.',
 'https://github.com/cvg/LightGlue')
add('geometry-compare','ecc','幾何四種工具，負責的工作不同','D',['共同工作','四種可見操作','依缺口選用'],
 '先分清校正、找對應與微調，再安排自己的定位流程。',
 'Compare work roles, not accuracy ranking. Same metal bracket camera setup across page. Exactly three major groups: common camera/part input, 2x2 compact central grouped comparison, final choice. Central subpanels each must contain substantial distinct operation: ChArUco printed board multiple tilts to camera grid/parameter file label「建立相機幾何」; SIFT local notch gradient histogram to matched point pairs label「局部描述找對應」; LightGlue ambiguous two hole connections with context unique notch then one selected match label「學習上下文配對」; ECC two same-hole outline overlays shift to coincide label「合理起點後微調」. These FOUR alternatives inside central group are NOT sequential; no arrows between alternative panels. All arrows only inside their own operation. Final small branch question「缺的是什麼？」 with camera/grid, corresponding points, fine overlay output examples respectively; no generic heatmap or pass/fail board. Keep necessary text short, role differences visible without paragraphs. Same task explanation not direct replacement or timing ranking. Concept illustration.',
 'https://docs.opencv.org/4.13.0/dc/d6b/group__video__track.html')
add('dino-core','det-dino-detector','DINO detector：先練辨別帶噪框，再學會出框','C',['訓練有真值','正負去噪訊號','推論只有影像'],
 '帶噪真值只幫助訓練；正式出框時沒有真值可偷看。',
 'Industrial tabletop with ONE hex-head bolt and ONE washer, realistic top-down gray mat, each fixed location throughout. Three main regions. First TRAINING annotated image with tight GREEN GT rectangle around bolt, label「人工真值框」, green means known annotation not quality pass. Second TRAINING big crop same bolt with blue solid near perturbed query box and orange dashed farther perturbed query box; green thin GT remains reference. Split targets visibly: near blue box arrow toward green GT and label「正樣本：還原真值框／類別」; farther orange box points to separate empty-class symbol label「負樣本：學無物件」, it is a training query not a real negative object, bolt remains visible. Label「對比去噪訓練」. Third clearly separate INFERENCE lane below/within last region: fresh unannotated same bolt+washer image → trained detector queries refine bounding boxes → two blue class-labeled rectangles「螺栓」「墊圈」. No green GT or noisy-query arrow feeds inference input. Small weight-file arrow from training to trained detector only. Subtitle「DETR系偵測器｜不是DINOv2特徵骨幹｜示意」. Large box movement and training-only boundary, no equation or invented performance.',
 'https://arxiv.org/abs/2203.03605')
add('dino-failure','det-dino-detector','訓練去噪，不能保證遮擋後仍找得到','D',['同一螺栓與墊圈','完整可見與遮擋','逐件對照人工標註'],
 '去噪訓練改善學習訊號；現場遮擋與漏檢仍要實測。',
 'Same top-down gray mat ONE bolt upper-left, ONE washer lower-right. Two same-scale condition views: fully visible input yields illustrative candidate blue boxes on both; other SAME positions with opaque black fixture overlapping most washer, washer remains physically partly visible crescent and most hidden. Show only bolt candidate box in right output, missed washer identified with orange hand-review dotted locator labeled「人工核對：漏一件」, not model box. Label「完整可見」「夾具遮擋」. End third group pair overlay to GT list「螺栓／墊圈」with bolt found, washer missed and action「補遮擋樣本／改取像」. Avoid counts other than clearly 2 items/1 missed. Explicit「假設漏檢示意，非實測」. No ground-truth feed into inference, no implication DN noise equals real occlusion augmentation.',
 'https://arxiv.org/abs/2203.03605')
add('world-core','yolo-world','YOLO-World：把詞彙表示接到找框流程','C',['先準備詞彙表示','影像與文字共同整理','區域對詞彙出框'],
 '詞彙可預先編碼；能否找到現場物件仍要驗證。',
 'Same tabletop one bolt and one washer on gray mat. THREE groups, clear offline top row and online bottom row inside structure. Left vocabulary chips「螺栓」「墊圈」→ text encoder → two distinct descriptor strips labeled「預先編碼／快取」, file persists. Separately raw unboxed tabletop image enters visual backbone. Center feature patches from bolt/washer image interact with cached TEXT descriptors via arrows entering a grouped vision-language neck labeled「文字參與特徵整理」; keep text cache and image separate until this real interaction. Right show two region descriptor strips compared against SAME two vocabulary strips, matching cell highlighted, then original image with class-labeled rectangles bolt and washer. Text output is label+box, not freeform answer, no arrows from raw image directly to answer bypassing model. Weight training already done subtitle「預訓練開放詞彙偵測器｜教學示意」. Small note「固定詞彙可預計算；不是每張重編文字」. No exact scores, no quality superiority.',
 'https://arxiv.org/abs/2401.17270')
add('world-failure','yolo-world','文字寫了缺陷，不代表影像裡看得見','D',['同一螺栓細裂紋','可見細節與不足像素','回到影像及標註驗證'],
 '提示詞不能補回缺失像素；先確認缺陷看得見。',
 'Same bolt on gray mat, tiny hairline crack at exact upper-right hex head edge. LEFT enlarged high-detail head crop shows actual thin dark crack, RIGHT same crop heavily downsampled then enlarged so blocky pixels merge crack with edge, object shape stays same; literal condition「細節足夠」「像素不足」. Shared prompt chip「裂紋螺栓」feeds both same-model conditions, but do not make fabricated accurate detection on left; show candidate box around bolt and question「框到物件≠證明裂紋」. Final independent visual verification zoom at raw acquisition, capture scale change giving visible same crack and human annotation, action「提高取像解析度／標註驗證」. Three major groups common task, paired views, evidence-based action. A phrase is semantic label not boolean exclusion rule; do not illustrate a NOT operation. Explicit concept demonstration not model prediction.',
 'https://arxiv.org/abs/2401.17270')
add('detector-compare','det-dino-detector','找同一批零件：類別從哪裡來？','D',['同一螺栓與墊圈','固定類別與文字詞彙','核對結果與維護成本'],
 '用類別與資料維護需求選候選，再以同批影像比較。',
 'Same tabletop one bolt and one washer. Two clearly parallel alternatives within central group, no arrow between methods. DINO detector: annotated training photos with class ids bolt/washer → trained class head → bounding boxes in image, labeled「固定類別訓練」「換類別：標註／訓練」。YOLO-World: pretrained weights plus two text chips bolt/washer→ cached descriptor strips→ region-text matching→same-format boxes, labeled「文字詞彙提示」「换詞彙：重編／重新驗證」. DINO is not DINOv2 and no textual prompt input; YOLOWorld still pretrained, do not say no training ever. End common same-batch acceptance panel shows input file stack, box-to-human-label correspondence and stopwatch alongside manual review pile, label「同資料查漏檢、錯類與完整時間」. No fake timing bars or different heatmaps to rank quality. Three main groups common task, two alternatives, joint verification. Clear material details and class-origin flows, few words.',
 'https://arxiv.org/abs/2203.03605 ; https://arxiv.org/abs/2401.17270')
for r in rows:
 brief=f"# WI-032 {r['title']}\n- lesson objective: {r['takeaway']}\n- page type: {r['kind']} — 以具體機制或同條件對照說明工作選擇。\n- primary reading path: {r['nodes'][0]} → {r['nodes'][1]} → {r['nodes'][2]} → 依可見證據採取下一步\n- major visual nodes:\n"+''.join(f'  {i+1}. {n}\n' for i,n in enumerate(r['nodes']))+f"- named guide-conformant reference page: `{REF}` — 已實看，借材質、細框、主體比例；模型內容另設計。\n- pale-yellow takeaway: #FFF4CC：{r['takeaway']}\n- source: {r['source']}\n- evidence: AI生成教學示意；不冒充模型輸出、效能比較或可列印標靶。\n- generation: built-in imagegen；桌機16:9／手機直向另排；actual PNG review pending；user approval pending。\n\n## Visual brief／不變條件與可見證據\n{r['scene']}\n\n## Validation\nWI-031缺口轉換：方法造成的變化要能在圖上定位，不能重複同圖只换名稱；比較分支不串接。核對重複工件身份、來源箭頭、輸出責任、圖說／原生／桌機頁內／360px手機，固定v1.0逐項評。\n"
 (W/(r['id']+'-r01.md')).write_text(brief,encoding='utf-8')
(W/'visual-plan.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
sys.path.insert(0,str(C/'tools'))
from validate_teaching_preflight import validate
out=[validate(W/(r['id']+'-r01.md')) for r in rows]+[validate(W/'ecc-core-r01.md')]
(W/'preflight-validation.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Prepared',len(rows)+1,'distinct main-story briefs; ECC desktop prototype already generated')
