from pathlib import Path
import json,re,hashlib
c=Path(__file__).parents[2];o=Path(__file__).parent
h=(c/'docs/index.html').read_text('utf8');d=json.loads(re.search(r'<script id="course-data" type="application/json">(.*?)</script>',h,re.S)[1]);render=json.loads((o/'recheck-rendered-content.json').read_text('utf8'));by={x['id']:x for x in render['rows']}
notes={
'charuco':'已知角點、多視角內參與單張姿態分工清楚',
'ecc':'局部起點、相關值與獨立殘差界線清楚',
'sift':'尺度方向描述、matcher與幾何求解分工清楚',
'lightglue':'extractor相容、上下文及遮擋限制清楚',
'resnet':'殘差相加與背景捷徑、自測資料/容量取捨成立',
'convnext':'空間與通道分工、部署成本有條件',
'vit-classifier':'位置token與注意力非輪廓、分類/分割取捨成立',
'u-net':'C2：首步標題像素標註，正文卻是下採樣',
'segformer':'階層多尺度與語意/實例責任清楚',
'yolo-seg':'C2：第1、2步標題與正文錯位；主線原型/係數成立',
'keypoint-r-cnn':'逐件點名、ROI還原及非原生3D責任清楚',
'pose':'2D–3D、相機、多解與物理姿態驗證清楚',
'det-yolo-dense':'指定YOLOv8例，NMS不修框及密集漏件成立',
'det-rtdetr':'高效編碼、query及訓練一對一分工有交代',
'det-dino-detector':'去噪只訓練、mixed query正式推論已分開',
'det-grounding-dino-interface':'文字參與定位，框與外接mask分清',
'yolo-world':'詞彙編碼/快取、細裂可見性限制清楚',
'yoloe':'三提示模式與mask責任、分割偏差有交代',
'ad-patchcore':'固定CNN代表正常庫、子集成本取捨清楚',
'ad-padim':'同位置分布、馬氏尺度與對位限制清楚',
'ad-anomalydino':'DINOv2局部參考、免微調非免資料清楚',
'ad-subspacead':'PCA正常投影與全維零殘差極端例清楚',
'ad-stfpm':'固定教師/正常學生、多層差异和錯誤兩側清楚',
'ad-rd4ad':'反向特徵重建及可訓練瓶頸責任清楚',
'ad-efficientad':'C2：首步標題正常訓練，正文卻跳待測推論',
'ad-ae':'像素重建非真值；110差值可追算；漏檢誤報成立',
'ad-draem':'合成mask只監督；原圖/重建共同判別清楚',
'ad-uniad':'限制照抄與逐產品驗證清楚',
'ad-dinomaly':'原版Dropout訓練/推論分清，無無條件速度排名',
'ad-invad':'空間風格調制非狀態空間，特徵重建非逐張重訓',
'ad-diffad':'C1：主線兩尺度正確，展開一次forward矛盾',
'ad-ddad':'多步原圖條件、像素及適配特徵差異分清',
'ad-winclip':'人工提示、視窗聚合與WinCLIP+參考有區分',
'ad-anomalyclip':'輔助提示學習與目標零樣本有區分',
'ad-anomalygpt':'原生定位與對話、外部應用覆核已分清',
'frame-difference':'變化雙邊非兩物件；停住/閃光反例成立',
'background-subtraction':'更新背景、停留吸收與占位分工清楚',
'lucas-kanade':'稀疏追點假設與稠密光流同條件比較清楚',
'raft':'全配對/迭代與像素位移非物理量分清；題較容易',
'bytetrack':'兩階段關聯、完全遮擋與計數分工清楚；題較容易',
'convlstm':'C2：卷積更新標題對不上原論文用途正文',
'videomae':'C2：編碼重建標題對不上部署移除解碼器正文',
'v-jepa':'2024特徵預測、目標EMA與下游任務分清',
'dinov2':'預訓練表徵、檢索與異常下游分清',
'dinov3':'Gram訓練關係與推論下游分清，不因新版本排名',
'clip':'圖文排序、候選缺類及專用分類器基準清楚',
'siglip':'逐對含負配對、分數非校準正確率清楚',
'llava':'視覺投影、問答與影像不能推出根因分清',
'qwen-vl':'固定Qwen2-VL例，像素預算與OCR基準清楚',
'gemini-vision':'API能力不推定私有架構，格式/內容驗證分清',
'defectfill':'少量缺陷微調、LFS不驗物理、下游真實留出清楚',
'anomalydiffusion':'外觀/位置、缺漏遮罩與合成監督一致性清楚',
'tf-idg':'固定權重非免最佳化；跨材質及總生成成本清楚',
'controlnet':'條件控制分支、基礎權重固定及inpainting可組合',
'inpainting':'任務非單一模型，填圖非實體修復清楚',
'diffusion-restoration':'先驗/觀測、多解與非一律相同外迴圈有交代',
'deblur':'模糊退化與振鈴假影、取像基準清楚',
'super-resolution':'估計非新增相機觀測，同孔q多解及取像驗證清楚'}
assert len(notes)==len(d['topics'])==len(by)==58
lines=['# WI-041 58 課內容重查 coverage','',f'基準 docs HTML SHA-256：`{hashlib.sha256(h.encode()).hexdigest()}`。', '', '每列都重新讀過報告中列出的主線／機制／比較／首讀自測／遷移题字段。DOM證據包括預設與全部 details 展開的 innerText；這個表不代表全部深讀正文或图片已人工逐字／逐像素重審，也不使用舊分數。', '', '| 課程（route lesson） | 主線圖數 | 首讀題在預設DOM | 因果鏈在展開DOM | 本輪獨立閱讀判斷 |','|---|---:|---|---|---|']
rows=[]
for t in d['topics']:
 s=t['teachingStory'];r=by[t['id']];q=s['micro_example']['title'] in r['default'];mech=all(x['title'] in r['expanded'] and x['body'] in r['expanded'] for x in s['mechanism_steps']);row={'id':t['id'],'source':f"_course_content/topics/{t['id']}.json",'manual_fields_reviewed':True,'default_question_present':q,'expanded_mechanism_present':mech,'finding':notes[t['id']]};rows.append(row);lines.append(f"| `{t['id']}` | {len(s['beginner_path']['visuals'])} | {'是' if q else '待核對'} | {'是' if mech else '待核對'} | {notes[t['id']]} |")
(o/'recheck-content-coverage.md').write_text('\n'.join(lines)+'\n','utf8');(o/'recheck-content-coverage.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),'utf8');print('coverage',len(rows),'DOM mismatch',sum(not x['default_question_present'] or not x['expanded_mechanism_present'] for x in rows))
