    function supportingFigureHTML(chapter) {
      const desktop = chapter.desktop, mobile = chapter.mobile;
      return `<figure class="workplace-figure"><picture><source media="(max-width: 700px)" srcset="${escapeHTML(mobile.path)}" width="${mobile.size[0]}" height="${mobile.size[1]}"><img data-asset src="${escapeHTML(desktop.path)}" width="${desktop.size[0]}" height="${desktop.size[1]}" loading="lazy" decoding="async" alt="${escapeHTML(chapter.image_title)}"></picture><figcaption><span>${escapeHTML(chapter.image_title)}</span><button class="button" type="button" data-action="open-concept" data-title="${escapeHTML(chapter.image_title)}" data-image="${escapeHTML(matchMedia('(max-width: 700px)').matches ? mobile.path : desktop.path)}" data-alt="${escapeHTML(chapter.image_title)}">放大完整圖</button></figcaption></figure>`;
    }
    function productionExampleResult(candidate) {
      const row = candidate === "B" ? {found:20, falseAlarms:120, elapsed:75} : {found:19, falseAlarms:40, elapsed:50};
      return `<h4>候選 ${candidate === "B" ? "B" : "A"}：這一組假設結果代表什麼？</h4><dl class="workplace-metrics"><div><dt>漏掉的缺陷</dt><dd>${20-row.found} / 20 件</dd></div><div><dt>正常誤報</dt><dd>${row.falseAlarms} / 1000 件</dd></div><div><dt>全部待覆核</dt><dd>${row.found+row.falseAlarms} 件</dd></div><div><dt>每件完整自動流程 P95</dt><dd>${row.elapsed} ms</dd></div></dl><p>待覆核＝找回的缺陷 ${row.found}＋正常誤報 ${row.falseAlarms}。按每件覆核 20 秒，合計約 <strong>${((row.found+row.falseAlarms)*20/60).toFixed(1)} 分鐘</strong>，尚未包含排隊與其他工作。</p><p>${candidate === "B" ? "B 在這個小樣本少漏一件，但多出 81 件待覆核；測試中零漏檢不代表未來零漏檢。" : "A 在這個例子覆核較少、完整流程較短，但漏掉一件缺陷；是否可接受取決於事先訂定的需求。"}</p>`;
    }
    function productionExampleHTML() {
      return `<section class="workplace-example" aria-labelledby="example-title"><p class="eyebrow">可追算的假設例 · 不是模型實測</p><h3 id="example-title">少漏一件，會增加多少覆核？</h3><p>固定同一組 <strong>1000 件正常品＋20 件缺陷品</strong>，每件只算一次。兩個候選的設定在測試前固定；以下數字為教學假設。</p><div class="action-row" role="group" aria-label="比較兩組假設結果"><button type="button" class="button primary" data-action="production-candidate" data-candidate="A" aria-pressed="true">候選 A</button><button type="button" class="button" data-action="production-candidate" data-candidate="B" aria-pressed="false">候選 B</button></div><div class="production-example-result" aria-live="polite">${productionExampleResult("A")}</div><p>P95 是約 95% 的件數在此時間內完成；這裡指取像到自動結果可用，不含人工覆核。兩種時間分開列，避免把模型快當成整條作業快。</p></section>`;
    }
    function workplaceComparisonHTML() {
      return `<section class="workplace-comparison"><h2>把工作需求對到合適的起點</h2><div class="workplace-table-wrap" tabindex="0" role="region" aria-label="方法選擇對照表"><table><caption>先比較資料、輸出及換產品成本；沒有預設勝者</caption><thead><tr><th scope="col">工作與起點</th><th scope="col">要準備／交出什麼</th><th scope="col">換產品與完整成本</th></tr></thead><tbody><tr><th scope="row">固定邊緣：輪廓或模板</th><td>穩定取像與可核對幾何；交出差異或幾何候選。</td><td>重設模板／規則，驗姿態與反光；計入誤報與覆核。</td></tr><tr><th scope="row">正常品為主：正常參考</th><td>乾淨正常參考、獨立缺陷驗證；交出異常分數／位置線索。</td><td>補參考、重建庫或復驗；計入特徵比對、記憶體及覆核。</td></tr><tr><th scope="row">已知缺陷：監督式分割</th><td>一致的像素標註與測試；交出預測區域，仍可能有邊界錯誤。</td><td>查新外觀與標註定義，必要時補標／重訓；計入訓練及維護。</td></tr><tr><th scope="row">尺寸判定：校正量測</th><td>可觀測幾何、尺度與誤差驗證；交出有條件的量測結果。</td><td>重查取像、尺度和重複性；輪廓提示只是可能的前一步。</td></tr></tbody></table></div></section>`;
    }
    function workplaceHandoffHTML(view) {
      return `<section class="workplace-handoff"><h2>${view === "foundations" ? "開始試做前，交出一份能核對的問題" : "啟用前，把接手流程寫到能演練"}</h2><ol>${(view === "foundations" ? ["寫清楚檢查哪個部位、要候選或尺寸、誰用結果。", "整理原圖與工件編號，分開建置、調參和獨立驗證資料。", "保留一個簡單基準，約定錯誤、耗時與人工覆核的比較方式。", "列出看不清楚或資料不足時的處置，不能把未驗證寫成通過。"] : ["固定版本、取像、資料、門檻與每件決策規則，保留重播證據。", "離線及旁觀分別記錄漏檢、正常誤報、完整延遲與覆核量。", "指定停用、待檢工件接手與恢復的負責人，演練服務失敗及影像失效。", "小範圍試行後依證據擴展；條件改變就重查參考、標註或模型適用性。"]).map(item=>`<li>${escapeHTML(item)}</li>`).join("")}</ol><div class="action-row"><button class="button primary" type="button" data-action="go" data-view="${view === "foundations" ? "production" : "poc"}">${view === "foundations" ? "接著看：從 POC 到量產 →" : "把條件帶入 POC 選型畫布 →"}</button><button class="button" type="button" data-action="go" data-view="${view === "foundations" ? "library" : "foundations"}">${view === "foundations" ? "依工作探索模型" : "回到共同前提"}</button></div></section>`;
    }
    function workplaceLessonHTML(view) {
      const lesson = DATA.workplaceLessons[view];
      return `<div class="content workplace-lesson" data-workplace="${view}"><header class="supporting-hero"><p class="eyebrow">${view === "foundations" ? "開始前：共同工程前提" : "從 POC 到量產"} · 三個工作案例</p><h1>${escapeHTML(lesson.title)}</h1><p class="supporting-intro">${escapeHTML(lesson.intro)}</p><p class="workplace-evidence">以下工件、圖像與流程為 AI 生成教學示意；不代表真實模型推論或產線驗收。</p></header><nav class="workplace-toc" aria-label="本頁閱讀順序">${lesson.chapters.map((c,i)=>`<a href="#${c.id}" data-action="workplace-scroll" data-workplace-anchor="${c.id}"><span>${i+1}</span>${escapeHTML(c.title)}</a>`).join("")}</nav>${lesson.chapters.map((c,i)=>`<section class="workplace-chapter" id="${c.id}" aria-labelledby="title-${c.id}"><header><p class="eyebrow">案例 ${i+1} / 3</p><h2 id="title-${c.id}">${escapeHTML(c.title)}</h2><p>${escapeHTML(c.case)}</p></header>${supportingFigureHTML(c)}<div class="workplace-explanation"><h3>為什麼會這樣？</h3><p>${escapeHTML(c.principle)}</p><ul>${c.points.map(p=>`<li>${escapeHTML(p)}</li>`).join("")}</ul><h3>放進工作時，怎麼選？</h3><p>${escapeHTML(c.tradeoff)}</p></div>${view === "production" && i === 1 ? productionExampleHTML() : ""}<div class="workplace-exercise"><h3>換個情境，先想再看解析</h3><p>${escapeHTML(c.question)}</p><details><summary>看解析與合理的替代選擇</summary><p>${escapeHTML(c.answer)}</p></details></div></section>`).join("")}${view === "foundations" ? workplaceComparisonHTML() : ""}${workplaceHandoffHTML(view)}<section class="workplace-sources"><h2>依據與延伸閱讀</h2><ul>${lesson.sources.map(s=>`<li><a href="${escapeHTML(s.url)}" target="_blank" rel="noopener">${escapeHTML(s.label)} ↗</a><p>${escapeHTML(s.scope)}</p></li>`).join("")}</ul><a href="${escapeHTML(lesson.source)}" target="_blank" rel="noopener">閱讀本頁 Markdown 原文 ↗</a></section><details class="workplace-legacy"><summary>原工程教材索引：${SUPPORTING[view].items.length} 個補充主題</summary><p>以下保留原工程圖供查閱；新版主線是上方三個案例，原圖未納入本輪首讀重評。</p>${SUPPORTING[view].items.map((item,i)=>`<details><summary>${i+1}. ${escapeHTML(item.title)}</summary>${supportingStoryHTML(item,i,SUPPORTING[view])}</details>`).join("")}</details></div>`;
    }
    function foundationsHTML() { return workplaceLessonHTML("foundations"); }
    function productionHTML() { return workplaceLessonHTML("production"); }
